/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package components;

import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import utils.DateValidation;
import utils.EmailValidation;
import utils.ICValidation;
import utils.PhoneNumberValidation;
import utils.FileManager;
import utils.NameValidation;
import utils.RoomValidation;
public class CreateBooking extends javax.swing.JFrame {

    /**
     * Creates new form EditBooking
     */
    public CreateBooking() {
        initComponents();
        StartingDate.setMinSelectableDate(new Date());
        EndingDate.setMinSelectableDate(new Date());
       DateValidation.checkdate(StartingDate,jLabel1);
       DateValidation.checkdate(EndingDate,jLabel2);
    }
     public boolean isInputValid() {
           boolean isNameValid, isICValid, isPhoneValid, isEmailValid,isDateValid;
           Customertxt.setInputVerifier(new NameValidation());
           ICnum.setInputVerifier(new ICValidation());
           Emailtxt.setInputVerifier(new EmailValidation());   
           Contactnumtxt.setInputVerifier(new PhoneNumberValidation());   
           isNameValid =  Customertxt.getInputVerifier().shouldYieldFocus(Customertxt);
           isICValid =  ICnum.getInputVerifier().shouldYieldFocus(ICnum);
           isPhoneValid = Contactnumtxt.getInputVerifier().shouldYieldFocus(Contactnumtxt);
           isEmailValid =  Emailtxt.getInputVerifier().shouldYieldFocus(Emailtxt);
           isDateValid = DateValidation.checkdate(StartingDate,EndingDate);
           return isNameValid && isICValid && isEmailValid && isPhoneValid && isDateValid;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jDateChooserBeanInfo1 = new com.toedter.calendar.JDateChooserBeanInfo();
        jCalendarTheme1 = new com.toedter.plaf.JCalendarTheme();
        birthdayEvaluator1 = new com.toedter.calendar.demo.BirthdayEvaluator();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        Nationality = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Donebtn = new javax.swing.JButton();
        ICnum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Contactnumtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Emailtxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Customertxt = new javax.swing.JTextField();
        Backbutton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        EndingDate = new com.toedter.calendar.JDateChooser();
        StartingDate = new com.toedter.calendar.JDateChooser();
        Malaysianbtn = new javax.swing.JRadioButton();
        nonMalaysianbtn = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Paxnum = new javax.swing.JComboBox<>();
        Clearbtn = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLabel10.setText("Starting Date Of Stay:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Booking");
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLabel3.setText("IC/Passport: ");

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLabel4.setText("Contact Number:");

        Donebtn.setBackground(new java.awt.Color(255, 51, 0));
        Donebtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        Donebtn.setForeground(new java.awt.Color(255, 255, 255));
        Donebtn.setText("Done");
        Donebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonebtnActionPerformed(evt);
            }
        });

        ICnum.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        ICnum.setSelectionColor(new java.awt.Color(51, 51, 255));
        ICnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICnumActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLabel5.setText("Email:");

        Contactnumtxt.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        Contactnumtxt.setSelectionColor(new java.awt.Color(51, 51, 255));
        Contactnumtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactnumtxtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLabel7.setText("Ending Date Of Stay:");

        Emailtxt.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        Emailtxt.setSelectionColor(new java.awt.Color(51, 51, 255));
        Emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailtxtActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLabel8.setText("Number of Pax:");

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 36)); // NOI18N
        jLabel1.setText("Create Booking");

        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLabel2.setText("Customer Name:");

        Customertxt.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        Customertxt.setSelectionColor(new java.awt.Color(51, 51, 255));
        Customertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomertxtActionPerformed(evt);
            }
        });

        Backbutton.setBackground(new java.awt.Color(255, 153, 153));
        Backbutton.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        Backbutton.setForeground(new java.awt.Color(51, 51, 0));
        Backbutton.setText("< Back");
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLabel11.setText("Starting Date Of Stay:");

        Nationality.add(Malaysianbtn);
        Malaysianbtn.setText("Malaysian");

        Nationality.add(nonMalaysianbtn);
        nonMalaysianbtn.setText("Non-Malaysian");

        jLabel6.setText("Nationality: ");

        Paxnum.setEditable(true);
        Paxnum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", " " }));

        Clearbtn.setText("Clear");
        Clearbtn.setMaximumSize(new java.awt.Dimension(61, 29));
        Clearbtn.setMinimumSize(new java.awt.Dimension(61, 29));
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(Donebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Customertxt)
                                .addComponent(ICnum)
                                .addComponent(Contactnumtxt)
                                .addComponent(Emailtxt)
                                .addComponent(EndingDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StartingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Paxnum, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Malaysianbtn)
                                .addGap(41, 41, 41)
                                .addComponent(nonMalaysianbtn)))))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Customertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ICnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Contactnumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(StartingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Paxnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(EndingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Malaysianbtn)
                        .addComponent(jLabel6))
                    .addComponent(nonMalaysianbtn))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Donebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ICnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICnumActionPerformed
         ICnum.setInputVerifier(new ICValidation());
    }//GEN-LAST:event_ICnumActionPerformed

    private void CustomertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomertxtActionPerformed
        Customertxt.setInputVerifier(new NameValidation());
    }//GEN-LAST:event_CustomertxtActionPerformed

    private void DonebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonebtnActionPerformed
             String name,ic, email,contactnum,pax,nationality = null;
             Date  startdate,enddate;
             name = Customertxt.getText();
             ic = ICnum.getText();
             contactnum =Contactnumtxt.getText();
             email = Emailtxt.getText();        
             startdate = StartingDate.getDate();
             enddate = EndingDate.getDate();
             pax =String.valueOf(Paxnum.getSelectedItem());
             if (Malaysianbtn.isSelected()){
                 nationality = Malaysianbtn.getText();
             }else if(nonMalaysianbtn.isSelected()){
                 nationality = nonMalaysianbtn.getText();
             }
             boolean inputsValid = RoomValidation.checkInputs(name, ic, contactnum, email, startdate, enddate, pax,nationality);
             if (inputsValid && isInputValid()){
                BookingDetails obj1 = new BookingDetails(name, ic, contactnum,email,startdate,enddate, pax,nationality);
                   String res = obj1.RecordBooking();
                   if(res.equals("Success")) {
                        JOptionPane.showMessageDialog(null, "Registration completed.", "Success", JOptionPane.INFORMATION_MESSAGE);
                           File textfile = new File("C:/Users/User/Documents/NetBeansProjects/Hotel Room/src/TextFiles/Booking.txt");
                            String[] content;
                            try {
                                content = FileManager.fileToArray(textfile);
                                int latestBooking = content.length - 1;
                                SelectRoom a = new SelectRoom(latestBooking);
                                a.setVisible(true);
                                this.setVisible(false);
                            } catch (IOException ex) {
                                Logger.getLogger(CreateBooking.class.getName()).log(Level.SEVERE, null, ex);
                            }

                    } else {            
                        JOptionPane.showMessageDialog(null, "Could not write into file due to " + res, "Error", JOptionPane.ERROR_MESSAGE);
                    }
 
        }
    }//GEN-LAST:event_DonebtnActionPerformed

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
        ViewRoom roompage = new ViewRoom();
        roompage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackbuttonActionPerformed

    private void EmailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailtxtActionPerformed
            Emailtxt.setInputVerifier(new EmailValidation());   
    }//GEN-LAST:event_EmailtxtActionPerformed

    private void ContactnumtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactnumtxtActionPerformed
                    Contactnumtxt.setInputVerifier(new PhoneNumberValidation());   
    }//GEN-LAST:event_ContactnumtxtActionPerformed

    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed
        Customertxt.setText("");
        ICnum.setText("");
        Contactnumtxt.setText("");
        Emailtxt.setText("");
        StartingDate.setDate(null);
        EndingDate.setDate(null);
        Paxnum.setSelectedIndex(0);
        Nationality.clearSelection();
    }//GEN-LAST:event_ClearbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutton;
    private javax.swing.JButton Clearbtn;
    private javax.swing.JTextField Contactnumtxt;
    private javax.swing.JTextField Customertxt;
    private javax.swing.JButton Donebtn;
    private javax.swing.JTextField Emailtxt;
    private com.toedter.calendar.JDateChooser EndingDate;
    private javax.swing.JTextField ICnum;
    private javax.swing.JRadioButton Malaysianbtn;
    private javax.swing.ButtonGroup Nationality;
    private javax.swing.JComboBox<String> Paxnum;
    private com.toedter.calendar.JDateChooser StartingDate;
    private com.toedter.calendar.demo.BirthdayEvaluator birthdayEvaluator1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.plaf.JCalendarTheme jCalendarTheme1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooserBeanInfo jDateChooserBeanInfo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton nonMalaysianbtn;
    // End of variables declaration//GEN-END:variables
}
