/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package components;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import utils.FileManager;
import static utils.RoomValidation.checkRoom;

/**
 *
 * @author User
 */
public class SelectRoom extends javax.swing.JFrame {
    private int lineIndex;
    private String textfile = "C:/Users/User/Documents/NetBeansProjects/Hotel Room/src/TextFiles/Booking.txt";
    private File file = new File(textfile);
    private List<String> matchingValues;

    /**
     * Creates new form SelectRoom
     */
    public SelectRoom(int lineIndex) {
        initComponents();
        setLocationRelativeTo(null);
        try {
            checkRoomStatus(lineIndex);
            this.lineIndex = lineIndex;
        } catch (IOException ex) {
            Logger.getLogger(SelectRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

public void checkRoomStatus(int lineIndex) throws IOException {
    JRadioButton[] rooms = {Room100,Room101, Room102, Room103, Room104, Room105, Room106, Room107, Room108, Room109, Room200,Room201, Room202, Room203, Room204, Room205, Room206, Room207, Room208, Room209};
    if(file.length() != 0) {
        matchingValues = checkRoom(lineIndex);                
        for (String value : matchingValues) {
            for (JRadioButton button : rooms) { 
                if (button.getText().equals(value)) {
                    button.setEnabled(false);
                    if (value.equals(FileManager.getIndexFromEachRow(textfile, 0)[lineIndex]) && value != null) {
                        button.setSelected(true);
                        button.setEnabled(true);
                    }
                }
            }
        }
    }
}



        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Room101 = new javax.swing.JRadioButton();
        Room102 = new javax.swing.JRadioButton();
        Room104 = new javax.swing.JRadioButton();
        Room103 = new javax.swing.JRadioButton();
        Room105 = new javax.swing.JRadioButton();
        Room106 = new javax.swing.JRadioButton();
        Room107 = new javax.swing.JRadioButton();
        Room109 = new javax.swing.JRadioButton();
        Room108 = new javax.swing.JRadioButton();
        Room203 = new javax.swing.JRadioButton();
        Room207 = new javax.swing.JRadioButton();
        Room209 = new javax.swing.JRadioButton();
        Room208 = new javax.swing.JRadioButton();
        Room201 = new javax.swing.JRadioButton();
        Room202 = new javax.swing.JRadioButton();
        Room205 = new javax.swing.JRadioButton();
        Room204 = new javax.swing.JRadioButton();
        Room206 = new javax.swing.JRadioButton();
        Donebtn = new javax.swing.JButton();
        Room100 = new javax.swing.JRadioButton();
        Room200 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select a Room");
        setBackground(new java.awt.Color(255, 153, 204));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 36)); // NOI18N
        jLabel1.setText("Select a Room");

        buttonGroup.add(Room101);
        Room101.setText("101");
        Room101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room101ActionPerformed(evt);
            }
        });

        buttonGroup.add(Room102);
        Room102.setText("102");
        Room102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room102ActionPerformed(evt);
            }
        });

        buttonGroup.add(Room104);
        Room104.setText("104");
        Room104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room104ActionPerformed(evt);
            }
        });

        buttonGroup.add(Room103);
        Room103.setText("103");

        buttonGroup.add(Room105);
        Room105.setText("105");

        buttonGroup.add(Room106);
        Room106.setText("106");

        buttonGroup.add(Room107);
        Room107.setText("107");

        buttonGroup.add(Room109);
        Room109.setText("109");

        buttonGroup.add(Room108);
        Room108.setText("108");

        buttonGroup.add(Room203);
        Room203.setText("203");

        buttonGroup.add(Room207);
        Room207.setText("207");

        buttonGroup.add(Room209);
        Room209.setText("209");

        buttonGroup.add(Room208);
        Room208.setText("208");

        buttonGroup.add(Room201);
        Room201.setText("201");
        Room201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room201ActionPerformed(evt);
            }
        });

        buttonGroup.add(Room202);
        Room202.setText("202");
        Room202.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room202ActionPerformed(evt);
            }
        });

        buttonGroup.add(Room205);
        Room205.setText("205");

        buttonGroup.add(Room204);
        Room204.setText("204");
        Room204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room204ActionPerformed(evt);
            }
        });

        buttonGroup.add(Room206);
        Room206.setText("206");

        Donebtn.setBackground(new java.awt.Color(255, 0, 0));
        Donebtn.setText("Done");
        Donebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonebtnActionPerformed(evt);
            }
        });

        buttonGroup.add(Room100);
        Room100.setText("100");

        buttonGroup.add(Room200);
        Room200.setText("200");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(Donebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Room102)
                            .addComponent(Room101)
                            .addComponent(Room103)
                            .addComponent(Room104)
                            .addComponent(Room105)
                            .addComponent(Room106)
                            .addComponent(Room107)
                            .addComponent(Room108)
                            .addComponent(Room109)
                            .addComponent(Room100))
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Room200)
                            .addComponent(Room202)
                            .addComponent(Room201)
                            .addComponent(Room203)
                            .addComponent(Room204)
                            .addComponent(Room205)
                            .addComponent(Room206)
                            .addComponent(Room207)
                            .addComponent(Room208)
                            .addComponent(Room209))))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Room100)
                    .addComponent(Room200))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Room101)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room102)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room103)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room104)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room105)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room106)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room107)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room108)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room109))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Room201)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room202)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room203)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room204)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room205)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room206)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room207)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room208)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room209)))
                .addGap(46, 46, 46)
                .addComponent(Donebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Room101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room101ActionPerformed



    }//GEN-LAST:event_Room101ActionPerformed

    private void Room104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room104ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room104ActionPerformed

    private void Room102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room102ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room102ActionPerformed

    private void Room201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room201ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room201ActionPerformed

    private void Room202ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room202ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room202ActionPerformed

    private void Room204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room204ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room204ActionPerformed

    private void DonebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonebtnActionPerformed
       JRadioButton[] rooms = {Room100, Room101, Room102, Room103, Room104, Room105, Room106, Room107, Room108, Room109, Room200, Room201, Room202, Room203, Room204, Room205, Room206, Room207, Room208, Room209};

        try {
            String roomText = "";
            for (JRadioButton room : rooms) {
                if (room.isSelected()) {
                    roomText = room.getText();
                    break; 
                }
            }
            if(roomText.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Please select one room.","Empty Room Selection Message", JOptionPane.INFORMATION_MESSAGE);
            }else{
                    boolean bookingStatus =FileManager.updateIndexContent(file, lineIndex, 0, roomText);
                    if(bookingStatus){
                            JOptionPane.showMessageDialog(null, "Booking created successfully.","Booking Completed Message", JOptionPane.INFORMATION_MESSAGE);
                    }
                     ViewRoom br = new ViewRoom();
                     br.setVisible(true);
                     this.setVisible(false);
            }
        } catch (IOException ex) {
            Logger.getLogger(SelectRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DonebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(int lineIndex) {
                new SelectRoom(lineIndex).setVisible(true);
            }

            @Override
            public void run() {
throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Donebtn;
    private javax.swing.JRadioButton Room100;
    private javax.swing.JRadioButton Room101;
    private javax.swing.JRadioButton Room102;
    private javax.swing.JRadioButton Room103;
    private javax.swing.JRadioButton Room104;
    private javax.swing.JRadioButton Room105;
    private javax.swing.JRadioButton Room106;
    private javax.swing.JRadioButton Room107;
    private javax.swing.JRadioButton Room108;
    private javax.swing.JRadioButton Room109;
    private javax.swing.JRadioButton Room200;
    private javax.swing.JRadioButton Room201;
    private javax.swing.JRadioButton Room202;
    private javax.swing.JRadioButton Room203;
    private javax.swing.JRadioButton Room204;
    private javax.swing.JRadioButton Room205;
    private javax.swing.JRadioButton Room206;
    private javax.swing.JRadioButton Room207;
    private javax.swing.JRadioButton Room208;
    private javax.swing.JRadioButton Room209;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
